name = "All of Create"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97dbf6d2b1ee29b74e1e3e60c2f9ca91dd0032218edd119b366225ca90438deb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
