name = "All of Create"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95587446432cadf45a7e5dc768455fa48d3a77d2aa7c5e67099c1f9ccf049746"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
