name = "All of Create"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "812e493f3f291e8999e1d2a256450ca60bdbe3684dfa0a531f016f184edc9a69"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
